## Document Clustering - Opinion review dataset

In [6]:
import pandas as pd
import glob ,os

path = r'C:\Users\DooDoo\Desktop\PerfectGuid수정ver01\data\OpinosisDataset1.0\topics'
all_files = glob.glob(os.path.join(path, "*data"))
filename_list = []
opinion_text = []

# extract filename, and contents to string
for file_ in all_files:
    df = pd.read_table(file_, index_col=None, header=0, encoding='latin1')
    
    filename_=file_.split('\\')[-1]
    filename = filename_.split('.')[0]
    
    filename_list.append(filename)
    opinion_text.append(df.to_string())
    
document_df = pd.DataFrame({'filename':filename_list, 'opinion_text':opinion_text})
document_df.head()

,filename,opinion_text
0,accuracy_garmin_nuvi_255W_gps,", and is very, very acc..."
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and..."
2,battery-life_amazon_kindle,After I plugged it in to my USB hub on my ...
3,battery-life_ipod_nano_8gb,short battery life I moved up from a...
4,battery-life_netbook_1005ha,"6GHz 533FSB cpu, glossy display, 3, Cell 2..."

### Write function for lemmatization

In [14]:
from nltk.stem import WordNetLemmatizer
import nltk
import string

#nltk
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
lemmar = WordNetLemmatizer()

def LemTokens(tokens):
    return [lemmar.lemmatize(token) for token in tokens]

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [15]:
### use TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english', ngram_range=(1,2), min_df=0.05, max_df=0.85)

feature_vect = tfidf_vect.fit_transform(document_df['opinion_text'])

C:\Users\DooDoo\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:386: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

### Cluster using Kmeans

In [16]:
from sklearn.cluster import KMeans

km_cluster = KMeans(n_clusters=5, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
cluster_centers = km_cluster.cluster_centers_

In [17]:
document_df['cluster_label'] = cluster_label
document_df.head()

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,", and is very, very acc...",3
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and...",0
2,battery-life_amazon_kindle,After I plugged it in to my USB hub on my ...,4
3,battery-life_ipod_nano_8gb,short battery life I moved up from a...,4
4,battery-life_netbook_1005ha,"6GHz 533FSB cpu, glossy display, 3, Cell 2...",4

In [19]:
document_df[document_df['cluster_label']==0].sort_values(by='filename')

,filename,opinion_text,cluster_label
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and...",0
32,room_holiday_inn_london,"We arrived at 23,30 hours and they could n...",0
30,rooms_bestwestern_hotel_sfo,"Great Location , Nice Rooms , Helpless...",0
31,rooms_swissotel_chicago,The Swissotel is one of our favorite hotel...,0

In [20]:
document_df[document_df['cluster_label']==1].sort_values(by='filename')

,filename,opinion_text,cluster_label
13,food_holiday_inn_london,The room was packed to capacity with queu...,1
14,food_swissotel_chicago,The food for our event was deli...,1
15,free_bestwestern_hotel_sfo,The wine reception is a great idea as it i...,1
20,location_bestwestern_hotel_sfo,"Good Value good location , ideal ...",1
21,location_holiday_inn_london,Great location for tube and we crammed in...,1
24,parking_bestwestern_hotel_sfo,Parking was expensive but I think this is ...,1
28,price_holiday_inn_london,"All in all, a normal chain hotel on a nice...",1
38,service_bestwestern_hotel_sfo,Both of us having worked in tourism for o...,1
39,service_holiday_inn_london,"not customer, oriented hotelvery low servi...",1
40,service_swissotel_hotel_chicago,Mediocre room and service for a very extr...,1
45,staff_bestwestern_hotel_sfo,Staff are friendly and hel...,1
46,staff_swissotel_chicago,The staff at Swissotel were not particula...,1

In [21]:
document_df[document_df['cluster_label']==2].sort_values(by='filename')

,filename,opinion_text,cluster_label
6,comfort_honda_accord_2008,"Drivers seat not comfortable, the car its...",2
7,comfort_toyota_camry_2007,Ride seems comfortable and gas mileage fa...,2
16,gas_mileage_toyota_camry_2007,Ride seems comfortable and gas mileage fa...,2
17,interior_honda_accord_2008,I love the new body style and the interior...,2
18,interior_toyota_camry_2007,"First of all, the interior has way too ma...",2
22,mileage_honda_accord_2008,"It's quiet, get good gas mileage and look...",2
25,performance_honda_accord_2008,"Very happy with my 08 Accord, performance i...",2
29,quality_toyota_camry_2007,I previously owned a Toyota 4Runner which ...,2
37,seats_honda_accord_2008,Front seats are very uncomfor...,2
47,transmission_toyota_camry_2007,"After slowing down, transmission has to b...",2

In [23]:
document_df[document_df['cluster_label']==3].sort_values(by='filename')

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,", and is very, very acc...",3
5,buttons_amazon_kindle,I thought it would be fitting to christen ...,3
8,directions_garmin_nuvi_255W_gps,You also get upscale features like spoken ...,3
9,display_garmin_nuvi_255W_gps,3 quot widescreen display was a ...,3
10,eyesight-issues_amazon_kindle,It feels as easy to read as the K1 but doe...,3
12,fonts_amazon_kindle,Being able to change the font sizes is aw...,3
23,navigation_amazon_kindle,"In fact, the entire navigation structure h...",3
27,price_amazon_kindle,"If a case was included, as with the Kindle...",3
33,satellite_garmin_nuvi_255W_gps,It's fast to acquire satel...,3
43,speed_garmin_nuvi_255W_gps,Another feature on the 255w is a display of...,3
48,updates_garmin_nuvi_255W_gps,Another thing to consider was that I paid $...,3
50,voice_garmin_nuvi_255W_gps,The voice prompts and maps are wonderful ...,3

In [24]:
document_df[document_df['cluster_label']==4].sort_values(by='filename')

,filename,opinion_text,cluster_label
2,battery-life_amazon_kindle,After I plugged it in to my USB hub on my ...,4
3,battery-life_ipod_nano_8gb,short battery life I moved up from a...,4
4,battery-life_netbook_1005ha,"6GHz 533FSB cpu, glossy display, 3, Cell 2...",4
11,features_windows7,"I had to uninstall anti, virus and selecte...",4
19,keyboard_netbook_1005ha,", I think the new keyboard rivals the gre...",4
26,performance_netbook_1005ha,The Eee Super Hybrid Engine utility lets u...,4
34,screen_garmin_nuvi_255W_gps,It is easy to read and when touching the...,4
35,screen_ipod_nano_8gb,"As always, the video screen is sharp and b...",4
36,screen_netbook_1005ha,Keep in mind that once you get in a room ...,4
41,size_asus_netbook_1005ha,A few other things I'd like to point out i...,4
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it a...,4
44,speed_windows7,"Windows 7 is quite simply faster, more sta...",4
49,video_ipod_nano_8gb,"I bought the 8, gig Ipod Nano that has the...",4

In [25]:
from sklearn.cluster import KMeans

km_cluster = KMeans(n_clusters=3, max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
cluster_centers = km_cluster.cluster_centers_

document_df['cluster_label'] = cluster_label
document_df.sort_values(by='cluster_label')

,filename,opinion_text,cluster_label
0,accuracy_garmin_nuvi_255W_gps,", and is very, very acc...",0
48,updates_garmin_nuvi_255W_gps,Another thing to consider was that I paid $...,0
47,transmission_toyota_camry_2007,"After slowing down, transmission has to b...",0
44,speed_windows7,"Windows 7 is quite simply faster, more sta...",0
43,speed_garmin_nuvi_255W_gps,Another feature on the 255w is a display of...,0
42,sound_ipod_nano_8gb,headphone jack i got a clear case for it a...,0
41,size_asus_netbook_1005ha,A few other things I'd like to point out i...,0
36,screen_netbook_1005ha,Keep in mind that once you get in a room ...,0
35,screen_ipod_nano_8gb,"As always, the video screen is sharp and b...",0
34,screen_garmin_nuvi_255W_gps,It is easy to read and when touching the...,0
33,satellite_garmin_nuvi_255W_gps,It's fast to acquire satel...,0
27,price_amazon_kindle,"If a case was included, as with the Kindle...",0
26,performance_netbook_1005ha,The Eee Super Hybrid Engine utility lets u...,0
49,video_ipod_nano_8gb,"I bought the 8, gig Ipod Nano that has the...",0
23,navigation_amazon_kindle,"In fact, the entire navigation structure h...",0
19,keyboard_netbook_1005ha,", I think the new keyboard rivals the gre...",0
50,voice_garmin_nuvi_255W_gps,The voice prompts and maps are wonderful ...,0
10,eyesight-issues_amazon_kindle,It feels as easy to read as the K1 but doe...,0
4,battery-life_netbook_1005ha,"6GHz 533FSB cpu, glossy display, 3, Cell 2...",0
3,battery-life_ipod_nano_8gb,short battery life I moved up from a...,0
8,directions_garmin_nuvi_255W_gps,You also get upscale features like spoken ...,0
9,display_garmin_nuvi_255W_gps,3 quot widescreen display was a ...,0
11,features_windows7,"I had to uninstall anti, virus and selecte...",0
12,fonts_amazon_kindle,Being able to change the font sizes is aw...,0
5,buttons_amazon_kindle,I thought it would be fitting to christen ...,0
2,battery-life_amazon_kindle,After I plugged it in to my USB hub on my ...,0
13,food_holiday_inn_london,The room was packed to capacity with queu...,1
39,service_holiday_inn_london,"not customer, oriented hotelvery low servi...",1
38,service_bestwestern_hotel_sfo,Both of us having worked in tourism for o...,1
1,bathroom_bestwestern_hotel_sfo,"The room was not overly big, but clean and...",1
15,free_bestwestern_hotel_sfo,The wine reception is a great idea as it i...,1
20,location_bestwestern_hotel_sfo,"Good Value good location , ideal ...",1
21,location_holiday_inn_london,Great location for tube and we crammed in...,1
45,staff_bestwestern_hotel_sfo,Staff are friendly and hel...,1
32,room_holiday_inn_london,"We arrived at 23,30 hours and they could n...",1
31,rooms_swissotel_chicago,The Swissotel is one of our favorite hotel...,1
30,rooms_bestwestern_hotel_sfo,"Great Location , Nice Rooms , Helpless...",1
40,service_swissotel_hotel_chicago,Mediocre room and service for a very extr...,1
28,price_holiday_inn_london,"All in all, a normal chain hotel on a nice...",1
14,food_swissotel_chicago,The food for our event was deli...,1
24,parking_bestwestern_hotel_sfo,Parking was expensive but I think this is ...,1
46,staff_swissotel_chicago,The staff at Swissotel were not particula...,1
17,interior_honda_accord_2008,I love the new body style and the interior...,2
37,seats_honda_accord_2008,Front seats are very uncomfor...,2
7,comfort_toyota_camry_2007,Ride seems comfortable and gas mileage fa...,2
16,gas_mileage_toyota_camry_2007,Ride seems comfortable and gas mileage fa...,2
29,quality_toyota_camry_2007,I previously owned a Toyota 4Runner which ...,2
22,mileage_honda_accord_2008,"It's quiet, get good gas mileage and look...",2
18,interior_toyota_camry_2007,"First of all, the interior has way too ma...",2
6,comfort_honda_accord_2008,"Drivers seat not comfortable, the car its...",2
25,performance_honda_accord_2008,"Very happy with my 08 Accord, performance i...",2

### take keyword for each clusters

In [29]:
cluster_centers = km_cluster.cluster_centers_
print('cluster_centers shape :', cluster_centers.shape)
print(cluster_centers)

cluster_centers shape : (3, 2409)
[[0.0174987  0.         0.         ... 0.         0.         0.00452955]
 [0.         0.00170335 0.0025537  ... 0.0032582  0.00349413 0.        ]
 [0.         0.00152566 0.         ... 0.         0.         0.        ]]

In [39]:
def get_cluster_details(cluster_model, cluster_data, feature_names, clusters_num, top_n_features=10):
    cluster_details={}
    
    # use argsort the get indexes of the top 10 features
    centroid_feature_ordered_ind = cluster_model.cluster_centers_.argsort()[:, ::-1]
    
    # get the file & feature names for each cluster
    for cluster_num in range(clusters_num):
        cluster_details[cluster_num] = {}
        cluster_details[cluster_num]['cluster'] = cluster_num
        
        # get n top features and names
        top_feature_indexes = centroid_feature_ordered_ind[cluster_num, :top_n_features]
        top_features = [feature_names[ind] for ind in top_feature_indexes]
        
        # get cluster center values for each feature
        top_feature_values = cluster_model.cluster_centers_[cluster_num, top_feature_indexes].tolist()
        
        cluster_details[cluster_num]['top_features'] = top_features
        cluster_details[cluster_num]['top_features_value'] = top_feature_values
        filenames = cluster_data[cluster_data['cluster_label']==cluster_num]['filename']
        filenames = filenames.values.tolist()
        cluster_details[cluster_num]['filenames']=filenames
    return cluster_details

### get top features and filenames

In [40]:
def print_cluster_details(cluster_details):
    for cluster_num, cluster_detail in cluster_details.items():
        print('####### Cluster {0}'.format(cluster_num))
        print('Top features:', cluster_detail['top_features'])
        print('Reviews filenames :',cluster_detail['filenames'][:7])
        print('==================================================')

In [41]:
feature_names = tfidf_vect.get_feature_names()

cluster_details = get_cluster_details(cluster_model=km_cluster, cluster_data=document_df,\
                                  feature_names=feature_names, clusters_num=3, top_n_features=10 )
print_cluster_details(cluster_details)

####### Cluster 0
Top features: ['screen', 'battery', 'life', 'battery life', 'keyboard', 'kindle', 'size', 'button', 'easy', 'voice']
Reviews filenames : ['accuracy_garmin_nuvi_255W_gps', 'battery-life_amazon_kindle', 'battery-life_ipod_nano_8gb', 'battery-life_netbook_1005ha', 'buttons_amazon_kindle', 'directions_garmin_nuvi_255W_gps', 'display_garmin_nuvi_255W_gps']
==================================================
####### Cluster 1
Top features: ['room', 'hotel', 'service', 'location', 'staff', 'food', 'clean', 'bathroom', 'parking', 'room wa']
Reviews filenames : ['bathroom_bestwestern_hotel_sfo', 'food_holiday_inn_london', 'food_swissotel_chicago', 'free_bestwestern_hotel_sfo', 'location_bestwestern_hotel_sfo', 'location_holiday_inn_london', 'parking_bestwestern_hotel_sfo']
==================================================
####### Cluster 2
Top features: ['interior', 'seat', 'mileage', 'comfortable', 'car', 'gas', 'gas mileage', 'comfort', 'ride', 'performance']
Reviews filenames : ['comfort_honda_accord_2008', 'comfort_toyota_camry_2007', 'gas_mileage_toyota_camry_2007', 'interior_honda_accord_2008', 'interior_toyota_camry_2007', 'mileage_honda_accord_2008', 'performance_honda_accord_2008']
==================================================